<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Product::insert([
            [
                'nama_produk' => 'Laptop ASUS',
                'harga'       => 7500000,
                'deskripsi'   => 'Laptop untuk kerja',
                'stok'        => 10,
                'gambar'      => 'laptop.jpg',
                'category_id' => 1,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Kaos Polos',
                'harga'       => 100000,
                'deskripsi'   => 'Kaos cotton combed',
                'stok'        => 20,
                'gambar'      => 'kaos.jpg',
                'category_id' => 2,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Makanan Ringan',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 3,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Point Coffe',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 4,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Kuaci',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 3,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Sari Gandum',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 3,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Qtela',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 3,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Beng beng',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 3,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Ale-Ale',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 4,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Good Day',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 4,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Sprite',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 4,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'BigCola',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 4,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Pocari Sweat',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 4,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Sukro',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 3,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Tiktak',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 3,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Pachos',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 3,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'Potato',
                'harga'       => 15000,
                'deskripsi'   => 'Snack enak',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 3,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
            [
                'nama_produk' => 'ExtraJoss',
                'harga'       => 1500,
                'deskripsi'   => 'Minuman penambah stamina',
                'stok'        => 50,
                'gambar'      => 'snack.jpg',
                'category_id' => 4,
                'created_at'  => now(),
                'updated_at'  => now(),
            ],
        ]);
    }
}
